source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.5"

gem "rails", "~> 7.2"
gem "pg", "~> 1.1"
gem "puma", "~> 6.0"
gem "bootsnap", require: false
gem "rack-cors"

# Auth
gem "devise"
gem "devise-jwt"

# Sérialisation JSON
gem "jsonapi-serializer"

# Import Excel
gem "roo"

# Variables d'environnement
gem "dotenv-rails"

# HTTP client (API Claude plus tard)
gem "faraday"

group :development do
  gem "rubocop-rails", require: false
end

group :development, :test do
  gem "pry-rails"
end
